### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by jiazhao8267** [rickyzhang82/V2Ray-Deep-Packet-Inspection#2]
Could you please share the data set you use？

**Comment by rickyzhang82** [comment]
Due to privacy concerns, I won’t share data collecting from my home network. But you could follow my data capturing guide and use my tool tcpsort for data collection on your own.

**Comment by jiazhao8267** [comment]
> Due to privacy concerns, I won’t share data collecting from my home network. But you could follow my data capturing guide and use my tool tcpsort for data collection on your own.

OK, thank.

**Comment by jiazhao8267** [comment]
> Due to privacy concerns, I won’t share data collecting from my home network. But you could follow my data capturing guide and use my tool tcpsort for data collection on your own.

OK, thank. But can you share the format of the dataset?

**Comment by rickyzhang82** [comment]
It is first 16 TCP packets between two endpoints. See step 2: https://github.com/rickyzhang82/V2Ray-Deep-Packet-Inspection/blob/master/V2Ray%20Deep%20Packet%20Inspection.ipynb
