### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by mega-optimus** [rickyzhang82/V2Ray-Deep-Packet-Inspection#3]
Can you analyze where do the salient features come from? The header (if yes which part) or the payload?
Thank you !

**Comment by rickyzhang82** [comment]
@mega-optimus 

Is it a feature request? Anyway, it is a good question I didn't think about it 4 years ago. But the way to do it is the following:

Let say the CNN classifier is function $C(I)$, where $I$ is the 16x1500 2D image (stack up the first 16 TCP packets with 1500 bytes).

 $sailent\ map = \|\frac{\partial C}{\partial I}\|$

The idea is very simple. The pixel that can change the value of $C(I)$ drastically plays an important role in classification decision. This can be easily implemented by tensorflow. I bet those pixels are very likely in the payload related to Golang HTTPS handshake.

**Comment by mega-optimus** [comment]
> @mega-optimus
> 
> Is it a feature request? Anyway, it is a good question I didn't think about it 4 years ago. But the way to do it is the following:
> 
> Let say the CNN classifier is function C(I), where I is the 16x1500 2D image (stack up the first 16 TCP packets with 1500 bytes).
> 
> sailent map=|∂C∂I|
> 
> The idea is very simple. The pixel that can change the value of C(I) drastically plays an important role in classification decision. This can be easily implemented by tensorflow. I bet those pixels are very likely in the payload related to Golang HTTPS handshake.

Thanks for the reply!
It's just a question, not feature request.

**Comment by rickyzhang82** [comment]
@mega-optimus 

I tried my idea. Unfortunately, all gradient values are zero. It is likely that the activation function ReLU causes the saturated gradients. Imagine any negative value is 0.

I will dig further and see if I can find something helpful.
